
# Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
#Load given dataset
data = pd.read_csv("alzheimer.csv")

Before drop the given dataset:

In [4]:
data.head(10)

Group M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0  Nondemented   M   87    14  2.0  27.0  0.0  1987  0.696  0.883
1  Nondemented   M   88    14  2.0  30.0  0.0  2004  0.681  0.876
2     Demented   M   75    12  NaN  23.0  0.5  1678  0.736  1.046
3     Demented   M   76    12  NaN  28.0  0.5  1738  0.713  1.010
4     Demented   M   80    12  NaN  22.0  0.5  1698  0.701  1.034
5  Nondemented   F   88    18  3.0  28.0  0.0  1215  0.710  1.444
6  Nondemented   F   90    18  3.0  27.0  0.0  1200  0.718  1.462
7  Nondemented   M   80    12  4.0  28.0  0.0  1689  0.712  1.039
8  Nondemented   M   83    12  4.0  29.0  0.5  1701  0.711  1.032
9  Nondemented   M   85    12  4.0  30.0  0.0  1699  0.705  1.033

In [5]:
#shape
data.shape

(373, 10)

In [7]:
data.size

3730

After drop the given dataset:

In [6]:
df = data.dropna()

In [7]:
df.head()

Group M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0  Nondemented   M   87    14  2.0  27.0  0.0  1987  0.696  0.883
1  Nondemented   M   88    14  2.0  30.0  0.0  2004  0.681  0.876
5  Nondemented   F   88    18  3.0  28.0  0.0  1215  0.710  1.444
6  Nondemented   F   90    18  3.0  27.0  0.0  1200  0.718  1.462
7  Nondemented   M   80    12  4.0  28.0  0.0  1689  0.712  1.039

In [8]:
#shape
df.shape

(354, 10)

In [9]:
df.columns

Index(['Group', 'M/F', 'Age', 'EDUC', 'SES', 'MMSE', 'CDR', 'eTIV', 'nWBV',
       'ASF'],
      dtype='object')

In [10]:
df.rename(columns={"M/F":"GENDER"}, inplace=True)

In [11]:
df.columns

Index(['Group', 'GENDER', 'Age', 'EDUC', 'SES', 'MMSE', 'CDR', 'eTIV', 'nWBV',
       'ASF'],
      dtype='object')

In [12]:
df["Group"].value_counts()

Nondemented    190
Demented       127
Converted       37
Name: Group, dtype: int64

In [13]:
df["Group"] = df['Group'].map({"Nondemented":"Nondemented", "Demented":"Demented", "Converted":"Demented"})

In [14]:
df.Group.value_counts()

Nondemented    190
Demented       164
Name: Group, dtype: int64

In [15]:
#To describe the dataframe
df.describe()

Age        EDUC         SES        MMSE         CDR  \
count  354.000000  354.000000  354.000000  354.000000  354.000000   
mean    77.033898   14.703390    2.460452   27.409605    0.271186   
std      7.811808    2.895662    1.134005    3.712626    0.370537   
min     60.000000    6.000000    1.000000    4.000000    0.000000   
25%     71.000000   12.000000    2.000000   27.000000    0.000000   
50%     77.000000   15.000000    2.000000   29.000000    0.000000   
75%     82.000000   16.750000    3.000000   30.000000    0.500000   
max     98.000000   23.000000    5.000000   30.000000    2.000000   

              eTIV        nWBV         ASF  
count   354.000000  354.000000  354.000000  
mean   1489.991525    0.729879    1.193780  
std     175.768462    0.037842    0.136821  
min    1106.000000    0.644000    0.876000  
25%    1358.250000    0.699000    1.100250  
50%    1470.500000    0.729000    1.193500  
75%    1595.250000    0.757000    1.292500  
max    2004.000000    0.837000    1.587000

In [16]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354 entries, 0 to 372
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Group   354 non-null    object 
 1   GENDER  354 non-null    object 
 2   Age     354 non-null    int64  
 3   EDUC    354 non-null    int64  
 4   SES     354 non-null    float64
 5   MMSE    354 non-null    float64
 6   CDR     354 non-null    float64
 7   eTIV    354 non-null    int64  
 8   nWBV    354 non-null    float64
 9   ASF     354 non-null    float64
dtypes: float64(5), int64(3), object(2)
memory usage: 30.4+ KB


In [17]:
df.GENDER.unique()

array(['M', 'F'], dtype=object)

In [18]:
df.Age.unique()

array([87, 88, 90, 80, 83, 85, 93, 95, 68, 69, 66, 78, 81, 82, 76, 77, 86,
       92, 84, 72, 61, 64, 71, 73, 74, 60, 62, 91, 79, 89, 70, 75, 94, 97,
       65, 67, 63, 96, 98], dtype=int64)

In [19]:
df.EDUC.unique()

array([14, 18, 12, 16,  8, 20, 13,  6, 17, 15, 23, 11], dtype=int64)

In [20]:
df.eTIV.unique()

array([1987, 2004, 1215, 1200, 1689, 1701, 1699, 1272, 1257, 1457, 1480,
       1447, 1482, 1333, 1323, 1230, 1212, 1225, 1602, 1590, 1651, 1668,
       1783, 1814, 1820, 1813, 1406, 1398, 1423, 1587, 1606, 1597, 1911,
       1926, 1313, 1316, 1247, 1250, 1420, 1445, 1365, 1360, 1358, 1353,
       1547, 1562, 1377, 1390, 1402, 1392, 1430, 1463, 1307, 1311, 1466,
       1450, 1460, 1453, 1336, 1329, 1359, 1361, 1349, 1477, 1487, 1483,
       1485, 1174, 1179, 1310, 1320, 1348, 1289, 1295, 1314, 1640, 1665,
       1451, 1331, 1332, 1317, 1322, 1476, 1433, 1414, 1695, 1708, 1712,
       1714, 1491, 1505, 1503, 1461, 1454, 1474, 1484, 1500, 1264, 1275,
       1362, 1456, 1599, 1569, 1580, 1315, 1308, 1324, 1416, 1408, 1654,
       1660, 1681, 1641, 1664, 1667, 1462, 1459, 1464, 1957, 1928, 1440,
       1438, 1455, 1444, 1428, 1475, 1470, 1471, 1692, 1707, 1724, 1720,
       1391, 1524, 1512, 1507, 1490, 1504, 1151, 1143, 1536, 1520, 1848,
       1931, 1631, 1662, 1492, 1478, 1548, 1556, 15

In [21]:
df.corr()

Age      EDUC       SES      MMSE       CDR      eTIV      nWBV  \
Age   1.000000 -0.024977 -0.046857  0.055880 -0.022759  0.040182 -0.526316   
EDUC -0.024977  1.000000 -0.722647  0.184459 -0.129440  0.267933 -0.019822   
SES  -0.046857 -0.722647  1.000000 -0.149219  0.076160 -0.261575  0.090095   
MMSE  0.055880  0.184459 -0.149219  1.000000 -0.705962 -0.019439  0.341381   
CDR  -0.022759 -0.129440  0.076160 -0.705962  1.000000  0.052361 -0.350086   
eTIV  0.040182  0.267933 -0.261575 -0.019439  0.052361  1.000000 -0.206668   
nWBV -0.526316 -0.019822  0.090095  0.341381 -0.350086 -0.206668  1.000000   
ASF  -0.031783 -0.251677  0.255576  0.027745 -0.063413 -0.989030  0.211150   

           ASF  
Age  -0.031783  
EDUC -0.251677  
SES   0.255576  
MMSE  0.027745  
CDR  -0.063413  
eTIV -0.989030  
nWBV  0.211150  
ASF   1.000000

Before Pre-Processing

In [22]:
df.head()

Group GENDER  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0  Nondemented      M   87    14  2.0  27.0  0.0  1987  0.696  0.883
1  Nondemented      M   88    14  2.0  30.0  0.0  2004  0.681  0.876
5  Nondemented      F   88    18  3.0  28.0  0.0  1215  0.710  1.444
6  Nondemented      F   90    18  3.0  27.0  0.0  1200  0.718  1.462
7  Nondemented      M   80    12  4.0  28.0  0.0  1689  0.712  1.039

Before Pre_Processing:

In [23]:
df.tail()

Group GENDER  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
368     Demented      M   82    16  1.0  28.0  0.5  1693  0.694  1.037
369     Demented      M   86    16  1.0  26.0  0.5  1688  0.675  1.040
370  Nondemented      F   61    13  2.0  30.0  0.0  1319  0.801  1.331
371  Nondemented      F   63    13  2.0  30.0  0.0  1327  0.796  1.323
372  Nondemented      F   65    13  2.0  30.0  0.0  1333  0.801  1.317

After Pre_Processing:

In [24]:
from sklearn.preprocessing import LabelEncoder

var = ['Group', 'GENDER', 'Age', 'EDUC', 'SES', 'MMSE', 'CDR', 'eTIV', 'nWBV',
       'ASF']

le = LabelEncoder()

for i in var:
    df[i] = le.fit_transform(df[i]).astype(int)

In [25]:
df.head()

Group  GENDER  Age  EDUC  SES  MMSE  CDR  eTIV  nWBV  ASF
0      1       1   27     5    1    14    0   274    35    1
1      1       1   28     5    1    17    0   275    20    0
5      1       0   28     9    2    15    0    13    48  242
6      1       0   30     9    2    14    0    10    56  245
7      1       1   20     3    3    15    0   226    50   47

In [26]:
df.tail()

Group  GENDER  Age  EDUC  SES  MMSE  CDR  eTIV  nWBV  ASF
368      0       1   22     7    0    15    1   228    33   46
369      0       1   26     7    0    13    1   225    14   48
370      1       0    1     4    1    17    0    47   125  209
371      1       0    3     4    1    17    0    52   123  205
372      1       0    5     4    1    17    0    56   125  202